/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        Person person = new Person("zhuzhu");
        String message = "Hello I am changjiang7,please recall me later";
        Mobile iPhone = new IPhone();
        person.makeACall(iPhone,message);
        Mobile androidMobile = new AndroidMobile();
        person.makeACall(androidMobile,message);
        
        IPhoneRobot iPhoneRobot = new IPhoneRobot();
        iPhoneRobot.makeACall(new IPhone(),message);

    }
}
